"use client";

import React from "react";
import Image from "next/image";
import { Sparkles, Download } from "lucide-react";
import { LearningState } from "@/types/learning-state";
import clsx from "clsx";

export function InfographicView({ state, onLoadMore, loading }: { state: LearningState, onLoadMore?: () => void, loading?: boolean }) {
    // Correct fallback: ensure summary_bullets is never undefined
    const summary = state.feedback_guidance?.summary_bullets || [
        `Analyzing ${state.personalized_path?.recommended_topic || state.learner_input}...`,
        "Decomposing system architecture...",
        "Mapping core dependencies...",
        "Optimizing learning flow..."
    ];

    return (
        <div className="p-8 h-full flex items-center justify-center overflow-y-auto no-scrollbar">
            <div className="max-w-xl w-full min-h-[400px] rounded-3xl bg-gradient-to-br from-gemini-primary/20 via-foreground/5 to-gemini-secondary/20 p-1">
                <div className="w-full h-full min-h-[392px] bg-background rounded-[22px] p-8 flex flex-col items-center justify-center text-center relative">
                    {/* Decorative elements */}
                    <div className="absolute top-0 left-0 w-32 h-32 bg-gemini-primary/10 blur-3xl -translate-x-1/2 -translate-y-1/2 pointer-events-none" />
                    <div className="absolute bottom-0 right-0 w-32 h-32 bg-gemini-secondary/10 blur-3xl translate-x-1/2 translate-y-1/2 pointer-events-none" />

                    <div className="flex justify-between items-center w-full mb-8 relative z-10">
                        <h3 id="infographic-title" className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-gemini-primary to-gemini-secondary">
                            {state.personalized_path?.recommended_topic || "Concept Overview"}
                        </h3>
                        {!loading && (
                            <button
                                onClick={() => onLoadMore && onLoadMore()}
                                className="px-4 py-2 rounded-full bg-gemini-primary/10 text-gemini-primary hover:bg-gemini-primary/20 transition-colors flex items-center gap-2 text-sm font-medium"
                            >
                                <Sparkles className="w-4 h-4" />
                                {state.infographic?.imageUrl && !state.infographic.imageUrl.includes("placeholder") && !state.infographic.imageUrl.includes("placehold.co") ? "Regenerate" : "Generate Visual"}
                            </button>
                        )}
                    </div>

                    {/* Placeholder Logic for "Nano Banana" Image */}
                    {state.infographic?.imageUrl && !state.infographic.imageUrl.includes("placeholder") && !state.infographic.imageUrl.includes("placehold.co") ? (
                        <div className="flex flex-col items-center w-full">
                            <div className="relative w-full max-w-md aspect-square mb-6 rounded-xl overflow-hidden shadow-2xl border-4 border-white/10 group">
                                {loading && (
                                    <div className="absolute inset-0 z-20 bg-black/40 backdrop-blur-sm flex flex-col items-center justify-center animate-fade-in">
                                        <div className="w-12 h-12 rounded-full border-4 border-gemini-primary border-t-transparent animate-spin mb-4" />
                                        <p className="text-white text-xs font-bold uppercase tracking-widest">Updating Visual...</p>
                                    </div>
                                )}
                                <Image
                                    src={state.infographic.imageUrl}
                                    alt={state.infographic.altText || "Generated Infographic"}
                                    fill
                                    className={clsx(
                                        "object-cover w-full h-full hover:scale-105 transition-transform duration-700",
                                        loading ? "blur-sm" : ""
                                    )}
                                />
                                <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-4">
                                    <p className="text-white text-xs font-mono uppercase tracking-widest">
                                        Generated by Nano Banana
                                    </p>
                                </div>
                            </div>

                            <div className="flex items-center gap-4">
                                <a
                                    href={state.infographic.imageUrl}
                                    download={`infographic-${new Date().getTime()}.png`}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="px-6 py-3 rounded-full bg-foreground/10 hover:bg-foreground/20 text-foreground font-medium transition-colors flex items-center gap-2"
                                >
                                    <Download className="w-4 h-4" />
                                    Download
                                </a>
                                <button
                                    onClick={() => onLoadMore && onLoadMore()}
                                    disabled={loading}
                                    className="px-6 py-3 rounded-full bg-gemini-primary/10 text-gemini-primary hover:bg-gemini-primary/20 transition-colors flex items-center gap-2 disabled:opacity-50"
                                >
                                    <Sparkles className="w-4 h-4" />
                                    Regenerate
                                </button>
                            </div>
                        </div>
                    ) : (
                        <div className="flex flex-col items-center w-full">
                            {loading ? (
                                <div className="py-20 flex flex-col items-center">
                                    <div className="w-20 h-20 relative mb-8">
                                        <div className="absolute inset-0 rounded-full border-8 border-gemini-primary/20" />
                                        <div className="absolute inset-0 rounded-full border-8 border-gemini-primary border-t-transparent animate-spin" />
                                        <Sparkles className="absolute inset-0 m-auto w-8 h-8 text-gemini-primary animate-pulse" />
                                    </div>
                                    <h4 className="text-xl font-bold text-foreground mb-2">Generating Masterpiece</h4>
                                    <p className="text-foreground/40 font-mono text-xs uppercase tracking-[0.3em] animate-pulse">Nano Banana Engine Active</p>
                                </div>
                            ) : (
                                <>
                                    <div className="grid gap-4 w-full mb-8">
                                        {summary.map((point, i) => (
                                            <div
                                                key={point}
                                                className="flex items-center gap-4 text-left p-4 rounded-xl bg-foreground/5 border border-foreground/10 animate-fade-in"
                                                style={{ animationDelay: `${i * 200}ms` }}
                                            >
                                                <div className="w-2 h-2 rounded-full bg-gemini-primary shrink-0" />
                                                <p className="text-lg text-foreground/80 font-medium">
                                                    {typeof point === 'string' ? point : JSON.stringify(point)}
                                                </p>
                                            </div>
                                        ))}
                                    </div>
                                    <button
                                        onClick={() => onLoadMore && onLoadMore()}
                                        className="px-8 py-4 rounded-full bg-gradient-to-r from-yellow-400 to-orange-500 text-black font-bold text-lg hover:scale-105 transition-transform shadow-xl shadow-orange-500/20 flex items-center gap-3"
                                    >
                                        <Sparkles className="w-5 h-5" />
                                        Generate Visual Infographic
                                    </button>
                                </>
                            )}
                            <p className="text-xs text-foreground/30 mt-3 font-mono">powered by Nano Banana</p>
                        </div>
                    )}

                    <div className="mt-8 flex items-center gap-6 text-foreground/20 text-sm font-mono uppercase tracking-[0.2em]">
                        <span>Infographic Mode</span>
                        <div className="w-1 h-1 rounded-full bg-foreground/10" />
                        <span>v1.0.4</span>
                    </div>
                </div>
            </div>
        </div>
    )
}
